name: deploy

on:
  push:
    branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Connect to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/hng13-stage0-devops
            git pull origin main
            sudo cp -r /home/ubuntu/hng13-stage0-devops/index.html /var/www/html/index.html
            sudo systemctl restart nginx
